sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.4"
before_install:
  # Commands below copied from: http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
addons:
  apt:
    packages:
    # install pandoc for use with pypandoc for converting the README
    # from markdown to RST
    - pandoc
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy scipy nose pandas matplotlib
  - source activate test-environment
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  # older human Ensembl releases
  - pyensembl install --release 75 --species human
  - pyensembl install --release 77 --species human
  - pyensembl install --release 81 --species human
  - pyensembl install --release 83 --species human
  # latest human Ensembl release
  - pyensembl install --release 84 --species human
  # mouse 
  - pyensembl install --release 83 --species mouse
  - pyensembl install --release 84 --species mouse
  # now actually run the tests, generate a coverage report and run linter
  - nosetests test --with-coverage --cover-package=varcode && ./lint.sh
after_success:
  coveralls
deploy:
  provider: pypi
  user: hammerlab
  password:
    secure: "H0prsAPV1n4ksLO0Zp4xq7SuGGRFmo9HhEcEtfPiSTyh8u4Zxbv/bPjyCLVDilBIKieQsuluV6jqoW6Px5LhUGZwq/k7RN7u1eNuahmpkIwWamjdsNORgvHte6inWNjKGo4GJLM232e2A50kkHnJKDZulfE8eGg4FrRQtfKSkik="
  on:
    branch: master
    tags: true
